// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConferenceRoom.proto

package grpc.conferenceRoom;

public interface BookConferenceRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookConferenceRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string timeslot = 2;</code>
   */
  java.lang.String getTimeslot();
  /**
   * <code>string timeslot = 2;</code>
   */
  com.google.protobuf.ByteString
      getTimeslotBytes();

  /**
   * <code>string conferenceRoomName = 4;</code>
   */
  java.lang.String getConferenceRoomName();
  /**
   * <code>string conferenceRoomName = 4;</code>
   */
  com.google.protobuf.ByteString
      getConferenceRoomNameBytes();
}
