// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConferenceRoom.proto

package grpc.conferenceRoom;

/**
 * Protobuf type {@code BookConferenceRoomRequest}
 */
public  final class BookConferenceRoomRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BookConferenceRoomRequest)
    BookConferenceRoomRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BookConferenceRoomRequest.newBuilder() to construct.
  private BookConferenceRoomRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BookConferenceRoomRequest() {
    date_ = "";
    timeslot_ = "";
    numParticipants_ = 0;
    conferanceRoomId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BookConferenceRoomRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            date_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            timeslot_ = s;
            break;
          }
          case 24: {

            numParticipants_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            conferanceRoomId_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.conferenceRoom.ConferenceRoomService.internal_static_BookConferenceRoomRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.conferenceRoom.ConferenceRoomService.internal_static_BookConferenceRoomRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.conferenceRoom.BookConferenceRoomRequest.class, grpc.conferenceRoom.BookConferenceRoomRequest.Builder.class);
  }

  public static final int DATE_FIELD_NUMBER = 1;
  private volatile java.lang.Object date_;
  /**
   * <code>string date = 1;</code>
   */
  public java.lang.String getDate() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      date_ = s;
      return s;
    }
  }
  /**
   * <code>string date = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDateBytes() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      date_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESLOT_FIELD_NUMBER = 2;
  private volatile java.lang.Object timeslot_;
  /**
   * <code>string timeslot = 2;</code>
   */
  public java.lang.String getTimeslot() {
    java.lang.Object ref = timeslot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeslot_ = s;
      return s;
    }
  }
  /**
   * <code>string timeslot = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTimeslotBytes() {
    java.lang.Object ref = timeslot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeslot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMPARTICIPANTS_FIELD_NUMBER = 3;
  private int numParticipants_;
  /**
   * <code>int32 numParticipants = 3;</code>
   */
  public int getNumParticipants() {
    return numParticipants_;
  }

  public static final int CONFERANCEROOMID_FIELD_NUMBER = 4;
  private volatile java.lang.Object conferanceRoomId_;
  /**
   * <code>string conferanceRoomId = 4;</code>
   */
  public java.lang.String getConferanceRoomId() {
    java.lang.Object ref = conferanceRoomId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      conferanceRoomId_ = s;
      return s;
    }
  }
  /**
   * <code>string conferanceRoomId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getConferanceRoomIdBytes() {
    java.lang.Object ref = conferanceRoomId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      conferanceRoomId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, date_);
    }
    if (!getTimeslotBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timeslot_);
    }
    if (numParticipants_ != 0) {
      output.writeInt32(3, numParticipants_);
    }
    if (!getConferanceRoomIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, conferanceRoomId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, date_);
    }
    if (!getTimeslotBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timeslot_);
    }
    if (numParticipants_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, numParticipants_);
    }
    if (!getConferanceRoomIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, conferanceRoomId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.conferenceRoom.BookConferenceRoomRequest)) {
      return super.equals(obj);
    }
    grpc.conferenceRoom.BookConferenceRoomRequest other = (grpc.conferenceRoom.BookConferenceRoomRequest) obj;

    boolean result = true;
    result = result && getDate()
        .equals(other.getDate());
    result = result && getTimeslot()
        .equals(other.getTimeslot());
    result = result && (getNumParticipants()
        == other.getNumParticipants());
    result = result && getConferanceRoomId()
        .equals(other.getConferanceRoomId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATE_FIELD_NUMBER;
    hash = (53 * hash) + getDate().hashCode();
    hash = (37 * hash) + TIMESLOT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeslot().hashCode();
    hash = (37 * hash) + NUMPARTICIPANTS_FIELD_NUMBER;
    hash = (53 * hash) + getNumParticipants();
    hash = (37 * hash) + CONFERANCEROOMID_FIELD_NUMBER;
    hash = (53 * hash) + getConferanceRoomId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.conferenceRoom.BookConferenceRoomRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.conferenceRoom.BookConferenceRoomRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.conferenceRoom.BookConferenceRoomRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.conferenceRoom.BookConferenceRoomRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.conferenceRoom.BookConferenceRoomRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.conferenceRoom.BookConferenceRoomRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.conferenceRoom.BookConferenceRoomRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.conferenceRoom.BookConferenceRoomRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.conferenceRoom.BookConferenceRoomRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.conferenceRoom.BookConferenceRoomRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.conferenceRoom.BookConferenceRoomRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.conferenceRoom.BookConferenceRoomRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.conferenceRoom.BookConferenceRoomRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BookConferenceRoomRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BookConferenceRoomRequest)
      grpc.conferenceRoom.BookConferenceRoomRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.conferenceRoom.ConferenceRoomService.internal_static_BookConferenceRoomRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.conferenceRoom.ConferenceRoomService.internal_static_BookConferenceRoomRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.conferenceRoom.BookConferenceRoomRequest.class, grpc.conferenceRoom.BookConferenceRoomRequest.Builder.class);
    }

    // Construct using grpc.conferenceRoom.BookConferenceRoomRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      date_ = "";

      timeslot_ = "";

      numParticipants_ = 0;

      conferanceRoomId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.conferenceRoom.ConferenceRoomService.internal_static_BookConferenceRoomRequest_descriptor;
    }

    @java.lang.Override
    public grpc.conferenceRoom.BookConferenceRoomRequest getDefaultInstanceForType() {
      return grpc.conferenceRoom.BookConferenceRoomRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.conferenceRoom.BookConferenceRoomRequest build() {
      grpc.conferenceRoom.BookConferenceRoomRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.conferenceRoom.BookConferenceRoomRequest buildPartial() {
      grpc.conferenceRoom.BookConferenceRoomRequest result = new grpc.conferenceRoom.BookConferenceRoomRequest(this);
      result.date_ = date_;
      result.timeslot_ = timeslot_;
      result.numParticipants_ = numParticipants_;
      result.conferanceRoomId_ = conferanceRoomId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.conferenceRoom.BookConferenceRoomRequest) {
        return mergeFrom((grpc.conferenceRoom.BookConferenceRoomRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.conferenceRoom.BookConferenceRoomRequest other) {
      if (other == grpc.conferenceRoom.BookConferenceRoomRequest.getDefaultInstance()) return this;
      if (!other.getDate().isEmpty()) {
        date_ = other.date_;
        onChanged();
      }
      if (!other.getTimeslot().isEmpty()) {
        timeslot_ = other.timeslot_;
        onChanged();
      }
      if (other.getNumParticipants() != 0) {
        setNumParticipants(other.getNumParticipants());
      }
      if (!other.getConferanceRoomId().isEmpty()) {
        conferanceRoomId_ = other.conferanceRoomId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.conferenceRoom.BookConferenceRoomRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.conferenceRoom.BookConferenceRoomRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object date_ = "";
    /**
     * <code>string date = 1;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string date = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string date = 1;</code>
     */
    public Builder setDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      date_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string date = 1;</code>
     */
    public Builder clearDate() {
      
      date_ = getDefaultInstance().getDate();
      onChanged();
      return this;
    }
    /**
     * <code>string date = 1;</code>
     */
    public Builder setDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      date_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object timeslot_ = "";
    /**
     * <code>string timeslot = 2;</code>
     */
    public java.lang.String getTimeslot() {
      java.lang.Object ref = timeslot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeslot_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timeslot = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimeslotBytes() {
      java.lang.Object ref = timeslot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeslot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timeslot = 2;</code>
     */
    public Builder setTimeslot(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeslot_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timeslot = 2;</code>
     */
    public Builder clearTimeslot() {
      
      timeslot_ = getDefaultInstance().getTimeslot();
      onChanged();
      return this;
    }
    /**
     * <code>string timeslot = 2;</code>
     */
    public Builder setTimeslotBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeslot_ = value;
      onChanged();
      return this;
    }

    private int numParticipants_ ;
    /**
     * <code>int32 numParticipants = 3;</code>
     */
    public int getNumParticipants() {
      return numParticipants_;
    }
    /**
     * <code>int32 numParticipants = 3;</code>
     */
    public Builder setNumParticipants(int value) {
      
      numParticipants_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numParticipants = 3;</code>
     */
    public Builder clearNumParticipants() {
      
      numParticipants_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object conferanceRoomId_ = "";
    /**
     * <code>string conferanceRoomId = 4;</code>
     */
    public java.lang.String getConferanceRoomId() {
      java.lang.Object ref = conferanceRoomId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conferanceRoomId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string conferanceRoomId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getConferanceRoomIdBytes() {
      java.lang.Object ref = conferanceRoomId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conferanceRoomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string conferanceRoomId = 4;</code>
     */
    public Builder setConferanceRoomId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      conferanceRoomId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string conferanceRoomId = 4;</code>
     */
    public Builder clearConferanceRoomId() {
      
      conferanceRoomId_ = getDefaultInstance().getConferanceRoomId();
      onChanged();
      return this;
    }
    /**
     * <code>string conferanceRoomId = 4;</code>
     */
    public Builder setConferanceRoomIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      conferanceRoomId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BookConferenceRoomRequest)
  }

  // @@protoc_insertion_point(class_scope:BookConferenceRoomRequest)
  private static final grpc.conferenceRoom.BookConferenceRoomRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.conferenceRoom.BookConferenceRoomRequest();
  }

  public static grpc.conferenceRoom.BookConferenceRoomRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BookConferenceRoomRequest>
      PARSER = new com.google.protobuf.AbstractParser<BookConferenceRoomRequest>() {
    @java.lang.Override
    public BookConferenceRoomRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BookConferenceRoomRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BookConferenceRoomRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BookConferenceRoomRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.conferenceRoom.BookConferenceRoomRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

