// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConferenceRoom.proto

package grpc.conferenceRoom;

public final class ConferenceRoomService {
  private ConferenceRoomService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAvailableRoomsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAvailableRoomsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAvailableRoomsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAvailableRoomsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookConferenceRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookConferenceRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookConferenceRoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookConferenceRoomResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OccupancyDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OccupancyDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ConferenceRoom.proto\"J\n\030GetAvailableRo" +
      "omsRequest\022\014\n\004date\030\001 \001(\t\022\014\n\004time\030\002 \001(\t\022\022" +
      "\n\nofficeName\030\003 \001(\t\"_\n\031GetAvailableRoomsR" +
      "esponse\022\014\n\004date\030\001 \001(\t\022\030\n\020conferanceRoomI" +
      "d\030\002 \001(\t\022\032\n\022timeslotsAvailable\030\003 \001(\t\"n\n\031B" +
      "ookConferenceRoomRequest\022\014\n\004date\030\001 \001(\t\022\020" +
      "\n\010timeslot\030\002 \001(\t\022\027\n\017numParticipants\030\003 \001(" +
      "\005\022\030\n\020conferanceRoomId\030\004 \001(\t\"-\n\032BookConfe" +
      "renceRoomResponse\022\017\n\007message\030\001 \001(\t\",\n\024Oc" +
      "cupancyDataRequest\022\024\n\014numOccupancy\030\001 \001(\005" +
      "\"\007\n\005Empty2\351\001\n\016ConferenceRoom\022N\n\021GetAvail" +
      "ableRooms\022\031.GetAvailableRoomsRequest\032\032.G" +
      "etAvailableRoomsResponse\"\0000\001\022O\n\022BookConf" +
      "erenceRoom\022\032.BookConferenceRoomRequest\032\033" +
      ".BookConferenceRoomResponse\"\000\0226\n\021SendOcc" +
      "upancyData\022\025.OccupancyDataRequest\032\006.Empt" +
      "y\"\000(\001B.\n\023grpc.conferenceRoomB\025Conference" +
      "RoomServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetAvailableRoomsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetAvailableRoomsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAvailableRoomsRequest_descriptor,
        new java.lang.String[] { "Date", "Time", "OfficeName", });
    internal_static_GetAvailableRoomsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetAvailableRoomsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAvailableRoomsResponse_descriptor,
        new java.lang.String[] { "Date", "ConferanceRoomId", "TimeslotsAvailable", });
    internal_static_BookConferenceRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BookConferenceRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookConferenceRoomRequest_descriptor,
        new java.lang.String[] { "Date", "Timeslot", "NumParticipants", "ConferanceRoomId", });
    internal_static_BookConferenceRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BookConferenceRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookConferenceRoomResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_OccupancyDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_OccupancyDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OccupancyDataRequest_descriptor,
        new java.lang.String[] { "NumOccupancy", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
