// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConferenceRoom.proto

package grpc.conferenceRoom;

public final class ConferenceRoomService {
  private ConferenceRoomService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAvailableRoomsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAvailableRoomsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAvailableRoomsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAvailableRoomsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookConferenceRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookConferenceRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookConferenceRoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookConferenceRoomResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OccupancyDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OccupancyDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OccupancyDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OccupancyDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ConferenceRoom.proto\":\n\030GetAvailableRo" +
      "omsRequest\022\014\n\004date\030\001 \001(\t\022\020\n\010timeslot\030\002 \001" +
      "(\t\"5\n\031GetAvailableRoomsResponse\022\030\n\020confe" +
      "renceRoomId\030\002 \001(\005\"n\n\031BookConferenceRoomR" +
      "equest\022\014\n\004date\030\001 \001(\t\022\020\n\010timeslot\030\002 \001(\t\022\027" +
      "\n\017numParticipants\030\003 \001(\005\022\030\n\020conferenceRoo" +
      "mId\030\004 \001(\005\"-\n\032BookConferenceRoomResponse\022" +
      "\017\n\007message\030\001 \001(\t\",\n\024OccupancyDataRequest" +
      "\022\024\n\014numOccupancy\030\001 \001(\005\"/\n\025OccupancyDataR" +
      "esponse\022\026\n\016totalOccupancy\030\001 \001(\0052\371\001\n\016Conf" +
      "erenceRoom\022N\n\021GetAvailableRooms\022\031.GetAva" +
      "ilableRoomsRequest\032\032.GetAvailableRoomsRe" +
      "sponse\"\0000\001\022O\n\022BookConferenceRoom\022\032.BookC" +
      "onferenceRoomRequest\032\033.BookConferenceRoo" +
      "mResponse\"\000\022F\n\021SendOccupancyData\022\025.Occup" +
      "ancyDataRequest\032\026.OccupancyDataResponse\"" +
      "\000(\001B.\n\023grpc.conferenceRoomB\025ConferenceRo" +
      "omServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetAvailableRoomsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetAvailableRoomsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAvailableRoomsRequest_descriptor,
        new java.lang.String[] { "Date", "Timeslot", });
    internal_static_GetAvailableRoomsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetAvailableRoomsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAvailableRoomsResponse_descriptor,
        new java.lang.String[] { "ConferenceRoomId", });
    internal_static_BookConferenceRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BookConferenceRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookConferenceRoomRequest_descriptor,
        new java.lang.String[] { "Date", "Timeslot", "NumParticipants", "ConferenceRoomId", });
    internal_static_BookConferenceRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BookConferenceRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookConferenceRoomResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_OccupancyDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_OccupancyDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OccupancyDataRequest_descriptor,
        new java.lang.String[] { "NumOccupancy", });
    internal_static_OccupancyDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_OccupancyDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OccupancyDataResponse_descriptor,
        new java.lang.String[] { "TotalOccupancy", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
