// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConferenceRoom.proto

package grpc.conferenceRoom;

public interface GetAvailableRoomsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAvailableRoomsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string conferanceRoomId = 2;</code>
   */
  java.lang.String getConferanceRoomId();
  /**
   * <code>string conferanceRoomId = 2;</code>
   */
  com.google.protobuf.ByteString
      getConferanceRoomIdBytes();

  /**
   * <code>string timeslotsAvailable = 3;</code>
   */
  java.lang.String getTimeslotsAvailable();
  /**
   * <code>string timeslotsAvailable = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimeslotsAvailableBytes();
}
