// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConferenceRoom.proto

package grpc.conferenceRoom;

public interface GetAvailableRoomsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAvailableRoomsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string time = 2;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 2;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string officeName = 3;</code>
   */
  java.lang.String getOfficeName();
  /**
   * <code>string officeName = 3;</code>
   */
  com.google.protobuf.ByteString
      getOfficeNameBytes();
}
