// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConferenceRoom.proto

package grpc.conferenceRoom;

public interface GetAvailableRoomsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAvailableRoomsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string conferenceRoomName = 2;</code>
   */
  java.lang.String getConferenceRoomName();
  /**
   * <code>string conferenceRoomName = 2;</code>
   */
  com.google.protobuf.ByteString
      getConferenceRoomNameBytes();
}
