// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConferenceRoom.proto

package grpc.conferenceRoom;

/**
 * Protobuf type {@code GetAvailableRoomsResponse}
 */
public  final class GetAvailableRoomsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetAvailableRoomsResponse)
    GetAvailableRoomsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAvailableRoomsResponse.newBuilder() to construct.
  private GetAvailableRoomsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAvailableRoomsResponse() {
    conferanceRoomId_ = "";
    timeslotsAvailable_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAvailableRoomsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            conferanceRoomId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            timeslotsAvailable_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.conferenceRoom.ConferenceRoomService.internal_static_GetAvailableRoomsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.conferenceRoom.ConferenceRoomService.internal_static_GetAvailableRoomsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.conferenceRoom.GetAvailableRoomsResponse.class, grpc.conferenceRoom.GetAvailableRoomsResponse.Builder.class);
  }

  public static final int CONFERANCEROOMID_FIELD_NUMBER = 2;
  private volatile java.lang.Object conferanceRoomId_;
  /**
   * <code>string conferanceRoomId = 2;</code>
   */
  public java.lang.String getConferanceRoomId() {
    java.lang.Object ref = conferanceRoomId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      conferanceRoomId_ = s;
      return s;
    }
  }
  /**
   * <code>string conferanceRoomId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getConferanceRoomIdBytes() {
    java.lang.Object ref = conferanceRoomId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      conferanceRoomId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESLOTSAVAILABLE_FIELD_NUMBER = 3;
  private volatile java.lang.Object timeslotsAvailable_;
  /**
   * <code>string timeslotsAvailable = 3;</code>
   */
  public java.lang.String getTimeslotsAvailable() {
    java.lang.Object ref = timeslotsAvailable_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeslotsAvailable_ = s;
      return s;
    }
  }
  /**
   * <code>string timeslotsAvailable = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTimeslotsAvailableBytes() {
    java.lang.Object ref = timeslotsAvailable_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeslotsAvailable_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getConferanceRoomIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, conferanceRoomId_);
    }
    if (!getTimeslotsAvailableBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timeslotsAvailable_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getConferanceRoomIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, conferanceRoomId_);
    }
    if (!getTimeslotsAvailableBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timeslotsAvailable_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.conferenceRoom.GetAvailableRoomsResponse)) {
      return super.equals(obj);
    }
    grpc.conferenceRoom.GetAvailableRoomsResponse other = (grpc.conferenceRoom.GetAvailableRoomsResponse) obj;

    boolean result = true;
    result = result && getConferanceRoomId()
        .equals(other.getConferanceRoomId());
    result = result && getTimeslotsAvailable()
        .equals(other.getTimeslotsAvailable());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONFERANCEROOMID_FIELD_NUMBER;
    hash = (53 * hash) + getConferanceRoomId().hashCode();
    hash = (37 * hash) + TIMESLOTSAVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + getTimeslotsAvailable().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.conferenceRoom.GetAvailableRoomsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.conferenceRoom.GetAvailableRoomsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.conferenceRoom.GetAvailableRoomsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.conferenceRoom.GetAvailableRoomsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.conferenceRoom.GetAvailableRoomsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.conferenceRoom.GetAvailableRoomsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.conferenceRoom.GetAvailableRoomsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.conferenceRoom.GetAvailableRoomsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.conferenceRoom.GetAvailableRoomsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.conferenceRoom.GetAvailableRoomsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.conferenceRoom.GetAvailableRoomsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.conferenceRoom.GetAvailableRoomsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.conferenceRoom.GetAvailableRoomsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetAvailableRoomsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetAvailableRoomsResponse)
      grpc.conferenceRoom.GetAvailableRoomsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.conferenceRoom.ConferenceRoomService.internal_static_GetAvailableRoomsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.conferenceRoom.ConferenceRoomService.internal_static_GetAvailableRoomsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.conferenceRoom.GetAvailableRoomsResponse.class, grpc.conferenceRoom.GetAvailableRoomsResponse.Builder.class);
    }

    // Construct using grpc.conferenceRoom.GetAvailableRoomsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      conferanceRoomId_ = "";

      timeslotsAvailable_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.conferenceRoom.ConferenceRoomService.internal_static_GetAvailableRoomsResponse_descriptor;
    }

    @java.lang.Override
    public grpc.conferenceRoom.GetAvailableRoomsResponse getDefaultInstanceForType() {
      return grpc.conferenceRoom.GetAvailableRoomsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.conferenceRoom.GetAvailableRoomsResponse build() {
      grpc.conferenceRoom.GetAvailableRoomsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.conferenceRoom.GetAvailableRoomsResponse buildPartial() {
      grpc.conferenceRoom.GetAvailableRoomsResponse result = new grpc.conferenceRoom.GetAvailableRoomsResponse(this);
      result.conferanceRoomId_ = conferanceRoomId_;
      result.timeslotsAvailable_ = timeslotsAvailable_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.conferenceRoom.GetAvailableRoomsResponse) {
        return mergeFrom((grpc.conferenceRoom.GetAvailableRoomsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.conferenceRoom.GetAvailableRoomsResponse other) {
      if (other == grpc.conferenceRoom.GetAvailableRoomsResponse.getDefaultInstance()) return this;
      if (!other.getConferanceRoomId().isEmpty()) {
        conferanceRoomId_ = other.conferanceRoomId_;
        onChanged();
      }
      if (!other.getTimeslotsAvailable().isEmpty()) {
        timeslotsAvailable_ = other.timeslotsAvailable_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.conferenceRoom.GetAvailableRoomsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.conferenceRoom.GetAvailableRoomsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object conferanceRoomId_ = "";
    /**
     * <code>string conferanceRoomId = 2;</code>
     */
    public java.lang.String getConferanceRoomId() {
      java.lang.Object ref = conferanceRoomId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conferanceRoomId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string conferanceRoomId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getConferanceRoomIdBytes() {
      java.lang.Object ref = conferanceRoomId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conferanceRoomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string conferanceRoomId = 2;</code>
     */
    public Builder setConferanceRoomId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      conferanceRoomId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string conferanceRoomId = 2;</code>
     */
    public Builder clearConferanceRoomId() {
      
      conferanceRoomId_ = getDefaultInstance().getConferanceRoomId();
      onChanged();
      return this;
    }
    /**
     * <code>string conferanceRoomId = 2;</code>
     */
    public Builder setConferanceRoomIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      conferanceRoomId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object timeslotsAvailable_ = "";
    /**
     * <code>string timeslotsAvailable = 3;</code>
     */
    public java.lang.String getTimeslotsAvailable() {
      java.lang.Object ref = timeslotsAvailable_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeslotsAvailable_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timeslotsAvailable = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTimeslotsAvailableBytes() {
      java.lang.Object ref = timeslotsAvailable_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeslotsAvailable_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timeslotsAvailable = 3;</code>
     */
    public Builder setTimeslotsAvailable(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeslotsAvailable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timeslotsAvailable = 3;</code>
     */
    public Builder clearTimeslotsAvailable() {
      
      timeslotsAvailable_ = getDefaultInstance().getTimeslotsAvailable();
      onChanged();
      return this;
    }
    /**
     * <code>string timeslotsAvailable = 3;</code>
     */
    public Builder setTimeslotsAvailableBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeslotsAvailable_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetAvailableRoomsResponse)
  }

  // @@protoc_insertion_point(class_scope:GetAvailableRoomsResponse)
  private static final grpc.conferenceRoom.GetAvailableRoomsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.conferenceRoom.GetAvailableRoomsResponse();
  }

  public static grpc.conferenceRoom.GetAvailableRoomsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAvailableRoomsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAvailableRoomsResponse>() {
    @java.lang.Override
    public GetAvailableRoomsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetAvailableRoomsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAvailableRoomsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAvailableRoomsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.conferenceRoom.GetAvailableRoomsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

