// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConferenceRoom.proto

package grpc.conferenceRoom;

public interface LiveOccupancyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LiveOccupancyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numPeople = 1;</code>
   */
  int getNumPeople();
}
