// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConferenceRoom.proto

package grpc.conferenceRoom;

public interface LiveOccupancyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LiveOccupancyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 totalOccupancy = 1;</code>
   */
  int getTotalOccupancy();
}
