// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConferenceRoom.proto

package grpc.conferenceRoom;

public interface OccupancyDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OccupancyDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numOccupancy = 1;</code>
   */
  int getNumOccupancy();
}
