// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClockInOut.proto

package grpc.clockInOut;

public interface ClockinRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClockinRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employeeId = 1;</code>
   */
  java.lang.String getEmployeeId();
  /**
   * <code>string employeeId = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmployeeIdBytes();
}
