// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClockInOut.proto

package grpc.clockInOut;

public interface ClockinResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClockinResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employeeId = 1;</code>
   */
  java.lang.String getEmployeeId();
  /**
   * <code>string employeeId = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmployeeIdBytes();

  /**
   * <code>string date = 2;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string timein = 3;</code>
   */
  java.lang.String getTimein();
  /**
   * <code>string timein = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimeinBytes();
}
