// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClockInOut.proto

package grpc.clockInOut;

/**
 * Protobuf type {@code ClockoutRequest}
 */
public  final class ClockoutRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ClockoutRequest)
    ClockoutRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClockoutRequest.newBuilder() to construct.
  private ClockoutRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClockoutRequest() {
    employeeId_ = "";
    break_ = "";
    endShift_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClockoutRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            employeeId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            break_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            endShift_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.clockInOut.ClockInClockOutService.internal_static_ClockoutRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.clockInOut.ClockInClockOutService.internal_static_ClockoutRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.clockInOut.ClockoutRequest.class, grpc.clockInOut.ClockoutRequest.Builder.class);
  }

  public static final int EMPLOYEEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object employeeId_;
  /**
   * <code>string employeeId = 1;</code>
   */
  public java.lang.String getEmployeeId() {
    java.lang.Object ref = employeeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      employeeId_ = s;
      return s;
    }
  }
  /**
   * <code>string employeeId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEmployeeIdBytes() {
    java.lang.Object ref = employeeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      employeeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BREAK_FIELD_NUMBER = 2;
  private volatile java.lang.Object break_;
  /**
   * <code>string break = 2;</code>
   */
  public java.lang.String getBreak() {
    java.lang.Object ref = break_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      break_ = s;
      return s;
    }
  }
  /**
   * <code>string break = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBreakBytes() {
    java.lang.Object ref = break_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      break_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENDSHIFT_FIELD_NUMBER = 3;
  private volatile java.lang.Object endShift_;
  /**
   * <code>string endShift = 3;</code>
   */
  public java.lang.String getEndShift() {
    java.lang.Object ref = endShift_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      endShift_ = s;
      return s;
    }
  }
  /**
   * <code>string endShift = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEndShiftBytes() {
    java.lang.Object ref = endShift_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endShift_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEmployeeIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, employeeId_);
    }
    if (!getBreakBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, break_);
    }
    if (!getEndShiftBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, endShift_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEmployeeIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, employeeId_);
    }
    if (!getBreakBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, break_);
    }
    if (!getEndShiftBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, endShift_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.clockInOut.ClockoutRequest)) {
      return super.equals(obj);
    }
    grpc.clockInOut.ClockoutRequest other = (grpc.clockInOut.ClockoutRequest) obj;

    boolean result = true;
    result = result && getEmployeeId()
        .equals(other.getEmployeeId());
    result = result && getBreak()
        .equals(other.getBreak());
    result = result && getEndShift()
        .equals(other.getEndShift());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EMPLOYEEID_FIELD_NUMBER;
    hash = (53 * hash) + getEmployeeId().hashCode();
    hash = (37 * hash) + BREAK_FIELD_NUMBER;
    hash = (53 * hash) + getBreak().hashCode();
    hash = (37 * hash) + ENDSHIFT_FIELD_NUMBER;
    hash = (53 * hash) + getEndShift().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.clockInOut.ClockoutRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.clockInOut.ClockoutRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.clockInOut.ClockoutRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.clockInOut.ClockoutRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.clockInOut.ClockoutRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.clockInOut.ClockoutRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.clockInOut.ClockoutRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.clockInOut.ClockoutRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.clockInOut.ClockoutRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.clockInOut.ClockoutRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.clockInOut.ClockoutRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.clockInOut.ClockoutRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.clockInOut.ClockoutRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ClockoutRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ClockoutRequest)
      grpc.clockInOut.ClockoutRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.clockInOut.ClockInClockOutService.internal_static_ClockoutRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.clockInOut.ClockInClockOutService.internal_static_ClockoutRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.clockInOut.ClockoutRequest.class, grpc.clockInOut.ClockoutRequest.Builder.class);
    }

    // Construct using grpc.clockInOut.ClockoutRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      employeeId_ = "";

      break_ = "";

      endShift_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.clockInOut.ClockInClockOutService.internal_static_ClockoutRequest_descriptor;
    }

    @java.lang.Override
    public grpc.clockInOut.ClockoutRequest getDefaultInstanceForType() {
      return grpc.clockInOut.ClockoutRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.clockInOut.ClockoutRequest build() {
      grpc.clockInOut.ClockoutRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.clockInOut.ClockoutRequest buildPartial() {
      grpc.clockInOut.ClockoutRequest result = new grpc.clockInOut.ClockoutRequest(this);
      result.employeeId_ = employeeId_;
      result.break_ = break_;
      result.endShift_ = endShift_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.clockInOut.ClockoutRequest) {
        return mergeFrom((grpc.clockInOut.ClockoutRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.clockInOut.ClockoutRequest other) {
      if (other == grpc.clockInOut.ClockoutRequest.getDefaultInstance()) return this;
      if (!other.getEmployeeId().isEmpty()) {
        employeeId_ = other.employeeId_;
        onChanged();
      }
      if (!other.getBreak().isEmpty()) {
        break_ = other.break_;
        onChanged();
      }
      if (!other.getEndShift().isEmpty()) {
        endShift_ = other.endShift_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.clockInOut.ClockoutRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.clockInOut.ClockoutRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object employeeId_ = "";
    /**
     * <code>string employeeId = 1;</code>
     */
    public java.lang.String getEmployeeId() {
      java.lang.Object ref = employeeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        employeeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string employeeId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmployeeIdBytes() {
      java.lang.Object ref = employeeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        employeeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string employeeId = 1;</code>
     */
    public Builder setEmployeeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      employeeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string employeeId = 1;</code>
     */
    public Builder clearEmployeeId() {
      
      employeeId_ = getDefaultInstance().getEmployeeId();
      onChanged();
      return this;
    }
    /**
     * <code>string employeeId = 1;</code>
     */
    public Builder setEmployeeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      employeeId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object break_ = "";
    /**
     * <code>string break = 2;</code>
     */
    public java.lang.String getBreak() {
      java.lang.Object ref = break_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        break_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string break = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBreakBytes() {
      java.lang.Object ref = break_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        break_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string break = 2;</code>
     */
    public Builder setBreak(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      break_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string break = 2;</code>
     */
    public Builder clearBreak() {
      
      break_ = getDefaultInstance().getBreak();
      onChanged();
      return this;
    }
    /**
     * <code>string break = 2;</code>
     */
    public Builder setBreakBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      break_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object endShift_ = "";
    /**
     * <code>string endShift = 3;</code>
     */
    public java.lang.String getEndShift() {
      java.lang.Object ref = endShift_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endShift_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string endShift = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEndShiftBytes() {
      java.lang.Object ref = endShift_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endShift_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string endShift = 3;</code>
     */
    public Builder setEndShift(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      endShift_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string endShift = 3;</code>
     */
    public Builder clearEndShift() {
      
      endShift_ = getDefaultInstance().getEndShift();
      onChanged();
      return this;
    }
    /**
     * <code>string endShift = 3;</code>
     */
    public Builder setEndShiftBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      endShift_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ClockoutRequest)
  }

  // @@protoc_insertion_point(class_scope:ClockoutRequest)
  private static final grpc.clockInOut.ClockoutRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.clockInOut.ClockoutRequest();
  }

  public static grpc.clockInOut.ClockoutRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClockoutRequest>
      PARSER = new com.google.protobuf.AbstractParser<ClockoutRequest>() {
    @java.lang.Override
    public ClockoutRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClockoutRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClockoutRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClockoutRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.clockInOut.ClockoutRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

