// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClockInOut.proto

package grpc.clockInOut;

public interface ClockoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClockoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 employeeId = 1;</code>
   */
  int getEmployeeId();

  /**
   * <code>string dateOut = 2;</code>
   */
  java.lang.String getDateOut();
  /**
   * <code>string dateOut = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateOutBytes();

  /**
   * <code>string timeOut = 3;</code>
   */
  java.lang.String getTimeOut();
  /**
   * <code>string timeOut = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimeOutBytes();
}
