// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClockInOut.proto

package grpc.clockInOut;

public interface ClockinRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClockinRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 employeeId = 1;</code>
   */
  int getEmployeeId();

  /**
   * <code>string dateIn = 2;</code>
   */
  java.lang.String getDateIn();
  /**
   * <code>string dateIn = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateInBytes();

  /**
   * <code>string timeIn = 3;</code>
   */
  java.lang.String getTimeIn();
  /**
   * <code>string timeIn = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimeInBytes();
}
