// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClockInOut.proto

package grpc.clockInOut;

public interface ClockoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClockoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employeeId = 1;</code>
   */
  java.lang.String getEmployeeId();
  /**
   * <code>string employeeId = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmployeeIdBytes();

  /**
   * <code>string break = 2;</code>
   */
  java.lang.String getBreak();
  /**
   * <code>string break = 2;</code>
   */
  com.google.protobuf.ByteString
      getBreakBytes();

  /**
   * <code>string endShift = 3;</code>
   */
  java.lang.String getEndShift();
  /**
   * <code>string endShift = 3;</code>
   */
  com.google.protobuf.ByteString
      getEndShiftBytes();
}
