// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClockInOut.proto

package grpc.clockInOut;

public interface ClockinResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClockinResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
