// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Printer.proto

package grpc.printer;

public final class PrinterService {
  private PrinterService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Document_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Document_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ScanFilesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ScanFilesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ScanFilesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ScanFilesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rPrinter.proto\"0\n\010Document\022\024\n\014documentN" +
      "ame\030\001 \001(\t\022\016\n\006copies\030\002 \001(\005\"(\n\020ScanFilesRe" +
      "quest\022\024\n\014documentName\030\001 \001(\t\"$\n\021ScanFiles" +
      "Response\022\017\n\007message\030\001 \001(\t2s\n\007Printer\0226\n\t" +
      "ScanFiles\022\021.ScanFilesRequest\032\022.ScanFiles" +
      "Response\"\000(\001\0220\n\022PrintsAllDocuments\022\t.Doc" +
      "ument\032\t.Document\"\000(\0010\001B \n\014grpc.printerB\016" +
      "PrinterServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Document_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Document_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Document_descriptor,
        new java.lang.String[] { "DocumentName", "Copies", });
    internal_static_ScanFilesRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ScanFilesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ScanFilesRequest_descriptor,
        new java.lang.String[] { "DocumentName", });
    internal_static_ScanFilesResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ScanFilesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ScanFilesResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
