// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Printer.proto

package grpc.printer;

public final class PrinterService {
  private PrinterService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrintsAllDocumentsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrintsAllDocumentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrintsAllDocumentsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrintsAllDocumentsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rPrinter.proto\"A\n\031PrintsAllDocumentsReq" +
      "uest\022\024\n\014documentName\030\001 \001(\t\022\016\n\006copies\030\002 \001" +
      "(\005\"B\n\032PrintsAllDocumentsResponse\022\024\n\014docu" +
      "mentName\030\001 \001(\t\022\016\n\006copies\030\002 \001(\0052^\n\007Printe" +
      "r\022S\n\022PrintsAllDocuments\022\032.PrintsAllDocum" +
      "entsRequest\032\033.PrintsAllDocumentsResponse" +
      "\"\000(\0010\001B \n\014grpc.printerB\016PrinterServiceP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PrintsAllDocumentsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PrintsAllDocumentsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrintsAllDocumentsRequest_descriptor,
        new java.lang.String[] { "DocumentName", "Copies", });
    internal_static_PrintsAllDocumentsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PrintsAllDocumentsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrintsAllDocumentsResponse_descriptor,
        new java.lang.String[] { "DocumentName", "Copies", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
