// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Printer.proto

package grpc.printer;

public interface ScanFilesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ScanFilesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string documentName = 1;</code>
   */
  java.lang.String getDocumentName();
  /**
   * <code>string documentName = 1;</code>
   */
  com.google.protobuf.ByteString
      getDocumentNameBytes();
}
