// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Printer.proto

package grpc.printer;

public interface scanDocumentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scanDocumentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string documentName = 1;</code>
   */
  java.lang.String getDocumentName();
  /**
   * <code>string documentName = 1;</code>
   */
  com.google.protobuf.ByteString
      getDocumentNameBytes();

  /**
   * <code>int32 numPages = 2;</code>
   */
  int getNumPages();
}
